---
- name: Cluster Monitoring
  hosts: zero
  become: true
  vars:
    force_prom_config: false
    force_alert_config: false
    force_gatus_config: false
  vars_files:
    - vars.yaml

  roles:
    - { role: apt, tags: apt }
    - { role: prometheus, tags: prometheus }
    - { role: alertmanager, tags: alertmanager }
    - { role: gatus, tags: gatus }
