---
- name: Cluster Monitoring
  hosts: zero
  become: true
  vars:
    force_prom_config: true
    force_alert_config: true
  vars_files:
    - vars.yaml

  roles:
    - { role: apt }
    - { role: prometheus }
    - { role: alertmanager }
