---
- name: Install alertmanager
  ansible.builtin.apt:
    name: prometheus-alertmanager
    state: present
  when: '"prometheus-alertmanager" not in ansible_facts.packages'

- name: Add alertmanager config
  ansible.builtin.template:
    src: alertmanager.yml.js
    dest: /etc/prometheus/alertmanager.yml
    owner: root
    group: root
    mode: '644'
  when: ("prometheus-alertmanager" not in ansible_facts.packages) or
        (force_alert_config == true)

- name: Add alerts config
  ansible.builtin.template:
    src: alert.yml.js
    dest: /etc/prometheus/alert.yml
    owner: root
    group: root
    mode: '644'
  when: ("prometheus-alertmanager" not in ansible_facts.packages) or
        (force_alert_config == true)

- name: Add message template config
  ansible.builtin.copy:
    src: notifications.tmpl
    dest: /etc/prometheus/notifications.tmpl
    owner: root
    group: root
    mode: '644'
  when: ("prometheus-alertmanager" not in ansible_facts.packages) or
        (force_alert_config == true)

- name: Enable alertmanager service
  ansible.builtin.service:
    name: prometheus-alertmanager
    enabled: true
    state: restarted
  when: ("prometheus-alertmanager" not in ansible_facts.packages) or
        (force_alert_config == true)

- name: Check Alertmanager ready
  uri:
    url: http://{{ ansible_host }}:9093/-/ready
    return_content: yes
  register: prometheus_ready
  until: prometheus_ready.status == 200 and "OK" in prometheus_ready.content
  retries: 10
  delay: 5
  when: ("prometheus-alertmanager" not in ansible_facts.packages) or
        (force_alert_config == true)

- name: Check Alertmanager health
  uri:
    url: http://{{ ansible_host }}:9093/-/healthy
    return_content: yes
  register: prometheus_health
  until: prometheus_health.status == 200 and "OK" in prometheus_health.content
  retries: 5
  delay: 5
  when: ("prometheus-alertmanager" not in ansible_facts.packages) or
        (force_alert_config == true)
